bankinggg/bankinggg/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from banks.views import hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('banks.urls')),
path('credentials/',include('credentials.urls'))
]



# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

bankinggg/banks/urls.py
from django.urls import path

from banks import views
from bankinggg import settings
from django.conf.urls.static import static
app_name='banks'

urlpatterns = [

    path('', views.hello, name='hello'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankinggg/credentials/urls.py
from django.urls import path

from credentials import views
from bankinggg import settings
from django.conf.urls.static import static

app_name = 'credentials'

urlpatterns = [

    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('new', views.new, name='new'),
    path('page', views.page, name='page'),
    path('message', views.message, name='message')



]

bankinggg/bank/models.py
from django.db import models

# Create your models here.

bankinggg/banks/models.py
from django.db import models

# Create your models here.

bankinggg/credentials/models.py
from django.db import models
from django.db.models import options


# Create your model
DISTRICT_CHOICES=(
    ('kannur','KANNUR'),
    ('eranakulam','ERANAKULAM'),
    ('malappuram','MALAPPURAM'),
    ('palakkad','PALAKKAD'),
    ('kollam','KOLLAM')
)
ACCOUNT_CHOICES=(
    ('current account','CURRENT ACCOUNT'),
    ('savings account','SAVINGS ACCOUNT')
)
class bankkk(models.Model):
    name=models.CharField(max_length=200)
    dob=models.DateField(max_length=8)
    age=models.IntegerField()
    Gender=models.CharField(max_length=100)
    phn=models.IntegerField()
    mail=models.EmailField(max_length=254)
    address=models.CharField(max_length=50)
    des=models.CharField(max_length=18,choices=DISTRICT_CHOICES)
    branch=models.CharField(max_length=18,choices=DISTRICT_CHOICES)
    accounttype=models.CharField(max_length=20,choices=ACCOUNT_CHOICES)
    materialprovide=models.BooleanField('debit card',default=False)
    materialprovide1 = models.BooleanField('credit card', default=False)
    materialprovide2 = models.BooleanField('cheque book', default=False)

bankinggg/credentials/forms.py
from django import forms
from.models import *

class BankForm(forms.ModelForm):
    class Meta:
        model=bankkk

        fields="__all__"

bankinggg/bank/views.py
from django.shortcuts import render

# Create your views here.

bankinggg/banks/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def hello(request):
    return render(request,"home.html")

bankinggg/credentials/views.py
from django.shortcuts import render, redirect
from . models import bankkk
from . forms import *
from django.contrib import messages
def login(request):
    return render(request,'login.html')
def register(request):
    return render(request,'register.html')
def new(request):
    return render(request,'new.html')
def page(request):
    form=BankForm
    mydict={
        'form':form
    }


    return render(request,'form.html',context=mydict)
def message(request):
    return render(request,'msg.html')

bankinggg/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{form.as_p}}
 <a class="active" href="{% url 'credentials:new' %}"></a>
 <a class="btn btn-warning" href="{% url 'banks:hello' %}"><button type="button" class="btn btn-secondary">Logout</button></a><br>

 <a class="btn btn-warning" href="{% url 'credentials:message' %}"><button type="button" class="btn btn-secondary">submit</button></a><br>
</body>
</html>

bankinggg/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'navstyle.css' %}">

</head>
<body>


<nav class="navbar navbar-dark bg-dark">

     <a class="active" href="{% url 'credentials:login' %}">LOGIN</a>
     <a class="active" href="{% url 'credentials:register' %}">REGISTER</a>

    <div class="dropdown">
  <button class="dropbtn">branch</button>
  <div class="dropdown-content">
    <a href="https://en.m.wikipedia.org/wiki/Kannur">KANNUR</a>

    <a href="https://en.m.wikipedia.org/wiki/Ernakulam">ERANAKULAM</a>
    <a href="https://en.m.wikipedia.org/wiki/Malappuram">MALAPPURAM</a>
      <a href="https://en.m.wikipedia.org/wiki/Palakkad">PALAKKAD</a>
      <a href="https://en.m.wikipedia.org/wiki/Kollam">KOLLAM</a>

  </div>
</div>



    <a class="btn btn-warning" href="{% url 'credentials:login' %}">Click Here</a>

</nav>
<div class="content-item">
    <img src="static/img.png" alt="" width="100%;height=100px;">

</div>
</body>
</html>

bankinggg/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>

<form action="login" method="post" >
     {% csrf_token %}
     <input type="text" name="username" placeholder="enter your username"><br>
  <input type="password" name="password" placeholder="enter your password"><br>

 <a class="active" href="{% url 'credentials:new' %}"><button type="button" class="btn btn-secondary">submit</button></a><br>
    <a class="active" href="{% url 'credentials:register' %}">Register Link</a><br>


</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>
</html>

bankinggg/templates/msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>complete</title>
</head>
<body>
application accepted<br>
  <a class="active" href="{% url 'banks:hello' %}">link</a>

</body>
</html>

bankinggg/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>newpage</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
<a class="btn btn-warning" href="{% url 'credentials:page' %}"><button type="button" class="btn btn-secondary">click!!!</button></a><br>


</nav>
</body>
</html>

bankinggg/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>REGISTRATION</h2>
<form action="register" method="post">
    {% csrf_token %}
  <input type="text" name="username" placeholder="enter your username"><br>

  <input type="password" name="password" placeholder="enter your password"><br>
  <input type="password" name="password1" placeholder="confirm your password"><br>
    <a class="btn btn-warning" href="{% url 'credentials:login' %}"><button type="button" class="btn btn-secondary">submit</button></a><br>



</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>
</html>